export const ADD_TODO = 'ADD_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const USER_SUCCESS_LOGIN = 'USER_SUCCESS_LOGIN';
export const USER_SUCCESS_LOGOUT = 'USER_SUCCESS_LOGOUT';
export const USER_REDIRECT = 'USER_REDIRECT';
